package com.luo.struts.bean;
// Generated 2017-4-22 18:08:38 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * THrCompanyAreas generated by hbm2java
 */
public class HrCompanyAreasInfo implements java.io.Serializable {

	private Long id;
	private Long companyId;
	private String areaName;
	private String areaNameRoot;
	private String areaNameSub;
	private Integer rankRoot;
	private Date createDate;
	private Date updateDate;

	public HrCompanyAreasInfo() {
	}

	public HrCompanyAreasInfo(Long companyId, String areaName, String areaNameRoot, String areaNameSub, Integer rankRoot,
			Date createDate, Date updateDate) {
		this.companyId = companyId;
		this.areaName = areaName;
		this.areaNameRoot = areaNameRoot;
		this.areaNameSub = areaNameSub;
		this.rankRoot = rankRoot;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Long companyId) {
		this.companyId = companyId;
	}

	public String getAreaName() {
		return this.areaName;
	}

	public void setAreaName(String areaName) {
		this.areaName = areaName;
	}

	public String getAreaNameRoot() {
		return this.areaNameRoot;
	}

	public void setAreaNameRoot(String areaNameRoot) {
		this.areaNameRoot = areaNameRoot;
	}

	public String getAreaNameSub() {
		return this.areaNameSub;
	}

	public void setAreaNameSub(String areaNameSub) {
		this.areaNameSub = areaNameSub;
	}

	public Integer getRankRoot() {
		return this.rankRoot;
	}

	public void setRankRoot(Integer rankRoot) {
		this.rankRoot = rankRoot;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
