package com.jite.hibgen.model;

// Generated 2015-6-4 14:43:18 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TUserProfileIntends generated by hbm2java
 */
public class TUserProfileIntends implements java.io.Serializable {

	private Long id;
	private Long userId;
	private Integer type;
	private String commonId;
	private String commonName;
	private String commonNameRoot;
	private String commonNameSub;
	private Date createDate;
	private Date updateDate;

	public TUserProfileIntends() {
	}

	public TUserProfileIntends(Long userId, Integer type, String commonId,
			String commonName, String commonNameRoot, String commonNameSub,
			Date createDate, Date updateDate) {
		this.userId = userId;
		this.type = type;
		this.commonId = commonId;
		this.commonName = commonName;
		this.commonNameRoot = commonNameRoot;
		this.commonNameSub = commonNameSub;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public String getCommonId() {
		return this.commonId;
	}

	public void setCommonId(String commonId) {
		this.commonId = commonId;
	}

	public String getCommonName() {
		return this.commonName;
	}

	public void setCommonName(String commonName) {
		this.commonName = commonName;
	}

	public String getCommonNameRoot() {
		return this.commonNameRoot;
	}

	public void setCommonNameRoot(String commonNameRoot) {
		this.commonNameRoot = commonNameRoot;
	}

	public String getCommonNameSub() {
		return this.commonNameSub;
	}

	public void setCommonNameSub(String commonNameSub) {
		this.commonNameSub = commonNameSub;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
