package com.jite.hibgen.model;
// Generated 2018-4-9 9:49:10 by Hibernate Tools 4.3.1.Final

/**
 * TUser generated by hbm2java
 */
public class TUser implements java.io.Serializable {

	private int id;
	private String name;
	private String password;

	public TUser() {
	}

	public TUser(int id) {
		this.id = id;
	}

	public TUser(int id, String name, String password) {
		this.id = id;
		this.name = name;
		this.password = password;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
