package com.jite.hibgen.model;
// Generated 2018-3-26 10:06:46 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * TApproveLogs generated by hbm2java
 */
public class TApproveLogs implements java.io.Serializable {

	private Long id;
	private Long companyId;
	private String fieldFrom;
	private String fieldTo;
	private Integer type;
	private Integer status;
	private String statusDesc;
	private Date createDate;
	private Long creator;
	private Date updateDate;
	private Long updater;

	public TApproveLogs() {
	}

	public TApproveLogs(Long companyId, String fieldFrom, String fieldTo, Integer type, Integer status,
			String statusDesc, Date createDate, Long creator, Date updateDate, Long updater) {
		this.companyId = companyId;
		this.fieldFrom = fieldFrom;
		this.fieldTo = fieldTo;
		this.type = type;
		this.status = status;
		this.statusDesc = statusDesc;
		this.createDate = createDate;
		this.creator = creator;
		this.updateDate = updateDate;
		this.updater = updater;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Long companyId) {
		this.companyId = companyId;
	}

	public String getFieldFrom() {
		return this.fieldFrom;
	}

	public void setFieldFrom(String fieldFrom) {
		this.fieldFrom = fieldFrom;
	}

	public String getFieldTo() {
		return this.fieldTo;
	}

	public void setFieldTo(String fieldTo) {
		this.fieldTo = fieldTo;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getStatusDesc() {
		return this.statusDesc;
	}

	public void setStatusDesc(String statusDesc) {
		this.statusDesc = statusDesc;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Long getCreator() {
		return this.creator;
	}

	public void setCreator(Long creator) {
		this.creator = creator;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Long getUpdater() {
		return this.updater;
	}

	public void setUpdater(Long updater) {
		this.updater = updater;
	}

}
