package com.jite.hibgen.model;
// Generated 2018-3-26 10:06:46 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * TBqjyAccount generated by hbm2java
 */
public class TBqjyAccount implements java.io.Serializable {

	private Long id;
	private Long accountId;
	private Integer division;
	private Integer type;
	private String number;
	private Integer votes;
	private Integer qq;
	private String idPhoto;
	private String personalPhotos;
	private String description;
	private String hobby;
	private String comment;
	private Date createDate;
	private Date updateDate;
	private Long updater;

	public TBqjyAccount() {
	}

	public TBqjyAccount(Long accountId, Integer division, Integer type, String number, Integer votes, Integer qq,
			String idPhoto, String personalPhotos, String description, String hobby, String comment, Date createDate,
			Date updateDate, Long updater) {
		this.accountId = accountId;
		this.division = division;
		this.type = type;
		this.number = number;
		this.votes = votes;
		this.qq = qq;
		this.idPhoto = idPhoto;
		this.personalPhotos = personalPhotos;
		this.description = description;
		this.hobby = hobby;
		this.comment = comment;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.updater = updater;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getAccountId() {
		return this.accountId;
	}

	public void setAccountId(Long accountId) {
		this.accountId = accountId;
	}

	public Integer getDivision() {
		return this.division;
	}

	public void setDivision(Integer division) {
		this.division = division;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	public Integer getVotes() {
		return this.votes;
	}

	public void setVotes(Integer votes) {
		this.votes = votes;
	}

	public Integer getQq() {
		return this.qq;
	}

	public void setQq(Integer qq) {
		this.qq = qq;
	}

	public String getIdPhoto() {
		return this.idPhoto;
	}

	public void setIdPhoto(String idPhoto) {
		this.idPhoto = idPhoto;
	}

	public String getPersonalPhotos() {
		return this.personalPhotos;
	}

	public void setPersonalPhotos(String personalPhotos) {
		this.personalPhotos = personalPhotos;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getHobby() {
		return this.hobby;
	}

	public void setHobby(String hobby) {
		this.hobby = hobby;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Long getUpdater() {
		return this.updater;
	}

	public void setUpdater(Long updater) {
		this.updater = updater;
	}

}
