package com.jite.hibgen.model;
// Generated 2018-3-26 10:06:46 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * TBqjyTest generated by hbm2java
 */
public class TBqjyTest implements java.io.Serializable {

	private Long id;
	private Long accountId;
	private String link;
	private String uniqueId;
	private String username;
	private String password;
	private String status;
	private String amcatId;
	private String firstName;
	private String logical;
	private String personality;
	private String comprehension;
	private String competency;
	private Date createDate;
	private Date updateDate;

	public TBqjyTest() {
	}

	public TBqjyTest(Long accountId, String link, String uniqueId, String username, String password, String status,
			String amcatId, String firstName, String logical, String personality, String comprehension,
			String competency, Date createDate, Date updateDate) {
		this.accountId = accountId;
		this.link = link;
		this.uniqueId = uniqueId;
		this.username = username;
		this.password = password;
		this.status = status;
		this.amcatId = amcatId;
		this.firstName = firstName;
		this.logical = logical;
		this.personality = personality;
		this.comprehension = comprehension;
		this.competency = competency;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getAccountId() {
		return this.accountId;
	}

	public void setAccountId(Long accountId) {
		this.accountId = accountId;
	}

	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	public String getUniqueId() {
		return this.uniqueId;
	}

	public void setUniqueId(String uniqueId) {
		this.uniqueId = uniqueId;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getAmcatId() {
		return this.amcatId;
	}

	public void setAmcatId(String amcatId) {
		this.amcatId = amcatId;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLogical() {
		return this.logical;
	}

	public void setLogical(String logical) {
		this.logical = logical;
	}

	public String getPersonality() {
		return this.personality;
	}

	public void setPersonality(String personality) {
		this.personality = personality;
	}

	public String getComprehension() {
		return this.comprehension;
	}

	public void setComprehension(String comprehension) {
		this.comprehension = comprehension;
	}

	public String getCompetency() {
		return this.competency;
	}

	public void setCompetency(String competency) {
		this.competency = competency;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
