package com.jite.hibgen.model;
// Generated 2018-3-26 10:06:46 by Hibernate Tools 4.3.1.Final

/**
 * TCommonPermission generated by hbm2java
 */
public class TCommonPermission implements java.io.Serializable {

	private Long id;
	private String modelName;
	private String permiDesc;
	private String permiValue;
	private Integer sortOrder;
	private String pageId;

	public TCommonPermission() {
	}

	public TCommonPermission(String modelName, String permiDesc, String permiValue, Integer sortOrder, String pageId) {
		this.modelName = modelName;
		this.permiDesc = permiDesc;
		this.permiValue = permiValue;
		this.sortOrder = sortOrder;
		this.pageId = pageId;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getModelName() {
		return this.modelName;
	}

	public void setModelName(String modelName) {
		this.modelName = modelName;
	}

	public String getPermiDesc() {
		return this.permiDesc;
	}

	public void setPermiDesc(String permiDesc) {
		this.permiDesc = permiDesc;
	}

	public String getPermiValue() {
		return this.permiValue;
	}

	public void setPermiValue(String permiValue) {
		this.permiValue = permiValue;
	}

	public Integer getSortOrder() {
		return this.sortOrder;
	}

	public void setSortOrder(Integer sortOrder) {
		this.sortOrder = sortOrder;
	}

	public String getPageId() {
		return this.pageId;
	}

	public void setPageId(String pageId) {
		this.pageId = pageId;
	}

}
