package com.jite.hibgen.model;
// Generated 2018-3-26 10:06:46 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * TCompany generated by hbm2java
 */
public class TCompany implements java.io.Serializable {

	private Long companyId;
	private String companyName;
	private String companyCode;
	private String legalRepresentative;
	private String address;
	private String businessScope;
	private String registrationNumber;
	private Date establishmentDate;
	private String businessContract;
	private String businessPhone;
	private String businessEmail;
	private String systemManageContract;
	private String systemManagePhone;
	private String systemManageEmail;
	private String webPath;
	private Date createdTime;
	private String state;
	private String companyPhone;
	private String companyFax;
	private String companyContact;
	private String testFlag;
	private Date testStartDate;
	private Date testEndDate;
	private Long createdId;
	private Long updatedId;
	private Date updatedTime;
	private String companyShorterName;
	private String companyIndustry;
	private String companyProperty;
	private Long employeeNum;
	private String logoImage;
	private String activeState;
	private String paidState;

	public TCompany() {
	}

	public TCompany(String companyName, String companyCode, String legalRepresentative, String address,
			String businessScope, String registrationNumber, Date establishmentDate, String businessContract,
			String businessPhone, String businessEmail, String systemManageContract, String systemManagePhone,
			String systemManageEmail, String webPath, Date createdTime, String state, String companyPhone,
			String companyFax, String companyContact, String testFlag, Date testStartDate, Date testEndDate,
			Long createdId, Long updatedId, Date updatedTime, String companyShorterName, String companyIndustry,
			String companyProperty, Long employeeNum, String logoImage, String activeState, String paidState) {
		this.companyName = companyName;
		this.companyCode = companyCode;
		this.legalRepresentative = legalRepresentative;
		this.address = address;
		this.businessScope = businessScope;
		this.registrationNumber = registrationNumber;
		this.establishmentDate = establishmentDate;
		this.businessContract = businessContract;
		this.businessPhone = businessPhone;
		this.businessEmail = businessEmail;
		this.systemManageContract = systemManageContract;
		this.systemManagePhone = systemManagePhone;
		this.systemManageEmail = systemManageEmail;
		this.webPath = webPath;
		this.createdTime = createdTime;
		this.state = state;
		this.companyPhone = companyPhone;
		this.companyFax = companyFax;
		this.companyContact = companyContact;
		this.testFlag = testFlag;
		this.testStartDate = testStartDate;
		this.testEndDate = testEndDate;
		this.createdId = createdId;
		this.updatedId = updatedId;
		this.updatedTime = updatedTime;
		this.companyShorterName = companyShorterName;
		this.companyIndustry = companyIndustry;
		this.companyProperty = companyProperty;
		this.employeeNum = employeeNum;
		this.logoImage = logoImage;
		this.activeState = activeState;
		this.paidState = paidState;
	}

	public Long getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Long companyId) {
		this.companyId = companyId;
	}

	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public String getCompanyCode() {
		return this.companyCode;
	}

	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}

	public String getLegalRepresentative() {
		return this.legalRepresentative;
	}

	public void setLegalRepresentative(String legalRepresentative) {
		this.legalRepresentative = legalRepresentative;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getBusinessScope() {
		return this.businessScope;
	}

	public void setBusinessScope(String businessScope) {
		this.businessScope = businessScope;
	}

	public String getRegistrationNumber() {
		return this.registrationNumber;
	}

	public void setRegistrationNumber(String registrationNumber) {
		this.registrationNumber = registrationNumber;
	}

	public Date getEstablishmentDate() {
		return this.establishmentDate;
	}

	public void setEstablishmentDate(Date establishmentDate) {
		this.establishmentDate = establishmentDate;
	}

	public String getBusinessContract() {
		return this.businessContract;
	}

	public void setBusinessContract(String businessContract) {
		this.businessContract = businessContract;
	}

	public String getBusinessPhone() {
		return this.businessPhone;
	}

	public void setBusinessPhone(String businessPhone) {
		this.businessPhone = businessPhone;
	}

	public String getBusinessEmail() {
		return this.businessEmail;
	}

	public void setBusinessEmail(String businessEmail) {
		this.businessEmail = businessEmail;
	}

	public String getSystemManageContract() {
		return this.systemManageContract;
	}

	public void setSystemManageContract(String systemManageContract) {
		this.systemManageContract = systemManageContract;
	}

	public String getSystemManagePhone() {
		return this.systemManagePhone;
	}

	public void setSystemManagePhone(String systemManagePhone) {
		this.systemManagePhone = systemManagePhone;
	}

	public String getSystemManageEmail() {
		return this.systemManageEmail;
	}

	public void setSystemManageEmail(String systemManageEmail) {
		this.systemManageEmail = systemManageEmail;
	}

	public String getWebPath() {
		return this.webPath;
	}

	public void setWebPath(String webPath) {
		this.webPath = webPath;
	}

	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getCompanyPhone() {
		return this.companyPhone;
	}

	public void setCompanyPhone(String companyPhone) {
		this.companyPhone = companyPhone;
	}

	public String getCompanyFax() {
		return this.companyFax;
	}

	public void setCompanyFax(String companyFax) {
		this.companyFax = companyFax;
	}

	public String getCompanyContact() {
		return this.companyContact;
	}

	public void setCompanyContact(String companyContact) {
		this.companyContact = companyContact;
	}

	public String getTestFlag() {
		return this.testFlag;
	}

	public void setTestFlag(String testFlag) {
		this.testFlag = testFlag;
	}

	public Date getTestStartDate() {
		return this.testStartDate;
	}

	public void setTestStartDate(Date testStartDate) {
		this.testStartDate = testStartDate;
	}

	public Date getTestEndDate() {
		return this.testEndDate;
	}

	public void setTestEndDate(Date testEndDate) {
		this.testEndDate = testEndDate;
	}

	public Long getCreatedId() {
		return this.createdId;
	}

	public void setCreatedId(Long createdId) {
		this.createdId = createdId;
	}

	public Long getUpdatedId() {
		return this.updatedId;
	}

	public void setUpdatedId(Long updatedId) {
		this.updatedId = updatedId;
	}

	public Date getUpdatedTime() {
		return this.updatedTime;
	}

	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}

	public String getCompanyShorterName() {
		return this.companyShorterName;
	}

	public void setCompanyShorterName(String companyShorterName) {
		this.companyShorterName = companyShorterName;
	}

	public String getCompanyIndustry() {
		return this.companyIndustry;
	}

	public void setCompanyIndustry(String companyIndustry) {
		this.companyIndustry = companyIndustry;
	}

	public String getCompanyProperty() {
		return this.companyProperty;
	}

	public void setCompanyProperty(String companyProperty) {
		this.companyProperty = companyProperty;
	}

	public Long getEmployeeNum() {
		return this.employeeNum;
	}

	public void setEmployeeNum(Long employeeNum) {
		this.employeeNum = employeeNum;
	}

	public String getLogoImage() {
		return this.logoImage;
	}

	public void setLogoImage(String logoImage) {
		this.logoImage = logoImage;
	}

	public String getActiveState() {
		return this.activeState;
	}

	public void setActiveState(String activeState) {
		this.activeState = activeState;
	}

	public String getPaidState() {
		return this.paidState;
	}

	public void setPaidState(String paidState) {
		this.paidState = paidState;
	}

}
