package com.jite.hibgen.model;
// Generated 2018-3-26 10:06:46 by Hibernate Tools 4.3.1.Final

/**
 * TGameFingerguess generated by hbm2java
 */
public class TGameFingerguess implements java.io.Serializable {

	private int itemId;
	private String itemName;
	private Integer count;

	public TGameFingerguess() {
	}

	public TGameFingerguess(int itemId, String itemName) {
		this.itemId = itemId;
		this.itemName = itemName;
	}

	public TGameFingerguess(int itemId, String itemName, Integer count) {
		this.itemId = itemId;
		this.itemName = itemName;
		this.count = count;
	}

	public int getItemId() {
		return this.itemId;
	}

	public void setItemId(int itemId) {
		this.itemId = itemId;
	}

	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

}
