package com.jite.hibgen.model;
// Generated 2018-3-26 10:06:46 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * TGameRecord generated by hbm2java
 */
public class TGameRecord implements java.io.Serializable {

	private Integer recordId;
	private String pfist;
	private String cfist;
	private String result;
	private Date gameDate;

	public TGameRecord() {
	}

	public TGameRecord(String pfist, String cfist, String result, Date gameDate) {
		this.pfist = pfist;
		this.cfist = cfist;
		this.result = result;
		this.gameDate = gameDate;
	}

	public Integer getRecordId() {
		return this.recordId;
	}

	public void setRecordId(Integer recordId) {
		this.recordId = recordId;
	}

	public String getPfist() {
		return this.pfist;
	}

	public void setPfist(String pfist) {
		this.pfist = pfist;
	}

	public String getCfist() {
		return this.cfist;
	}

	public void setCfist(String cfist) {
		this.cfist = cfist;
	}

	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	public Date getGameDate() {
		return this.gameDate;
	}

	public void setGameDate(Date gameDate) {
		this.gameDate = gameDate;
	}

}
