package com.jite.hibgen.model;
// Generated 2018-3-26 10:06:46 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * THrCompanyMedias generated by hbm2java
 */
public class THrCompanyMedias implements java.io.Serializable {

	private Long id;
	private Long companyId;
	private String mediaName;
	private String mediaUrl;
	private String mediaDesc;
	private Integer hotPosition;
	private Date createDate;
	private Date updateDate;

	public THrCompanyMedias() {
	}

	public THrCompanyMedias(Long companyId, String mediaName, String mediaUrl, String mediaDesc, Integer hotPosition,
			Date createDate, Date updateDate) {
		this.companyId = companyId;
		this.mediaName = mediaName;
		this.mediaUrl = mediaUrl;
		this.mediaDesc = mediaDesc;
		this.hotPosition = hotPosition;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Long companyId) {
		this.companyId = companyId;
	}

	public String getMediaName() {
		return this.mediaName;
	}

	public void setMediaName(String mediaName) {
		this.mediaName = mediaName;
	}

	public String getMediaUrl() {
		return this.mediaUrl;
	}

	public void setMediaUrl(String mediaUrl) {
		this.mediaUrl = mediaUrl;
	}

	public String getMediaDesc() {
		return this.mediaDesc;
	}

	public void setMediaDesc(String mediaDesc) {
		this.mediaDesc = mediaDesc;
	}

	public Integer getHotPosition() {
		return this.hotPosition;
	}

	public void setHotPosition(Integer hotPosition) {
		this.hotPosition = hotPosition;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
