package com.jite.hibgen.model;
// Generated 2018-3-26 10:06:46 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * THrJobRequire generated by hbm2java
 */
public class THrJobRequire implements java.io.Serializable {

	private Long id;
	private Long jobId;
	private String degree;
	private String sex;
	private String language;
	private String major;
	private String age;
	private String workYears;
	private Date createDate;
	private Long creater;
	private Date updateDate;

	public THrJobRequire() {
	}

	public THrJobRequire(Long jobId, String degree, String sex, String language, String major, String age,
			String workYears, Date createDate, Long creater, Date updateDate) {
		this.jobId = jobId;
		this.degree = degree;
		this.sex = sex;
		this.language = language;
		this.major = major;
		this.age = age;
		this.workYears = workYears;
		this.createDate = createDate;
		this.creater = creater;
		this.updateDate = updateDate;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getJobId() {
		return this.jobId;
	}

	public void setJobId(Long jobId) {
		this.jobId = jobId;
	}

	public String getDegree() {
		return this.degree;
	}

	public void setDegree(String degree) {
		this.degree = degree;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	public String getMajor() {
		return this.major;
	}

	public void setMajor(String major) {
		this.major = major;
	}

	public String getAge() {
		return this.age;
	}

	public void setAge(String age) {
		this.age = age;
	}

	public String getWorkYears() {
		return this.workYears;
	}

	public void setWorkYears(String workYears) {
		this.workYears = workYears;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Long getCreater() {
		return this.creater;
	}

	public void setCreater(Long creater) {
		this.creater = creater;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
