package com.jite.hibgen.model;
// Generated 2018-3-26 10:06:46 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * THrResumes generated by hbm2java
 */
public class THrResumes implements java.io.Serializable {

	private Long id;
	private Long jobId;
	private Long hrId;
	private Long accountId;
	private Long companyId;
	private Integer status;
	private Integer hrStatus;
	private Date createDate;
	private Date updateDate;
	private Date checkDate;
	private Date inviteDate;
	private Date handDate;

	public THrResumes() {
	}

	public THrResumes(Long jobId, Long hrId, Long accountId, Long companyId, Integer status, Integer hrStatus,
			Date createDate, Date updateDate, Date checkDate, Date inviteDate, Date handDate) {
		this.jobId = jobId;
		this.hrId = hrId;
		this.accountId = accountId;
		this.companyId = companyId;
		this.status = status;
		this.hrStatus = hrStatus;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.checkDate = checkDate;
		this.inviteDate = inviteDate;
		this.handDate = handDate;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getJobId() {
		return this.jobId;
	}

	public void setJobId(Long jobId) {
		this.jobId = jobId;
	}

	public Long getHrId() {
		return this.hrId;
	}

	public void setHrId(Long hrId) {
		this.hrId = hrId;
	}

	public Long getAccountId() {
		return this.accountId;
	}

	public void setAccountId(Long accountId) {
		this.accountId = accountId;
	}

	public Long getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Long companyId) {
		this.companyId = companyId;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Integer getHrStatus() {
		return this.hrStatus;
	}

	public void setHrStatus(Integer hrStatus) {
		this.hrStatus = hrStatus;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Date getCheckDate() {
		return this.checkDate;
	}

	public void setCheckDate(Date checkDate) {
		this.checkDate = checkDate;
	}

	public Date getInviteDate() {
		return this.inviteDate;
	}

	public void setInviteDate(Date inviteDate) {
		this.inviteDate = inviteDate;
	}

	public Date getHandDate() {
		return this.handDate;
	}

	public void setHandDate(Date handDate) {
		this.handDate = handDate;
	}

}
