package com.jite.hibgen.model;
// Generated 2018-3-26 10:06:46 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * THrViewuserlog generated by hbm2java
 */
public class THrViewuserlog implements java.io.Serializable {

	private Long id;
	private Long userId;
	private Long hrId;
	private Long companyId;
	private Date createDate;
	private Date updateDate;

	public THrViewuserlog() {
	}

	public THrViewuserlog(Long userId, Long hrId, Long companyId, Date createDate, Date updateDate) {
		this.userId = userId;
		this.hrId = hrId;
		this.companyId = companyId;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public Long getHrId() {
		return this.hrId;
	}

	public void setHrId(Long hrId) {
		this.hrId = hrId;
	}

	public Long getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Long companyId) {
		this.companyId = companyId;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
