package com.jite.hibgen.model;
// Generated 2018-3-26 10:06:46 by Hibernate Tools 4.3.1.Final

/**
 * TInsideLetter generated by hbm2java
 */
public class TInsideLetter implements java.io.Serializable {

	private TInsideLetterId id;

	public TInsideLetter() {
	}

	public TInsideLetter(TInsideLetterId id) {
		this.id = id;
	}

	public TInsideLetterId getId() {
		return this.id;
	}

	public void setId(TInsideLetterId id) {
		this.id = id;
	}

}
