package com.jite.hibgen.model;
// Generated 2018-3-26 10:06:46 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * TOrgInfo generated by hbm2java
 */
public class TOrgInfo implements java.io.Serializable {

	private Long id;
	private String fromSource;
	private String fromUrl;
	private String title;
	private String icon;
	private String images;
	private String description;
	private Integer visitSum;
	private String type;
	private String areaTags;
	private String workTags;
	private Integer rank;
	private Date createDate;
	private Date updateDate;

	public TOrgInfo() {
	}

	public TOrgInfo(String fromSource, String fromUrl, String title, String icon, String images, String description,
			Integer visitSum, String type, String areaTags, String workTags, Integer rank, Date createDate,
			Date updateDate) {
		this.fromSource = fromSource;
		this.fromUrl = fromUrl;
		this.title = title;
		this.icon = icon;
		this.images = images;
		this.description = description;
		this.visitSum = visitSum;
		this.type = type;
		this.areaTags = areaTags;
		this.workTags = workTags;
		this.rank = rank;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getFromSource() {
		return this.fromSource;
	}

	public void setFromSource(String fromSource) {
		this.fromSource = fromSource;
	}

	public String getFromUrl() {
		return this.fromUrl;
	}

	public void setFromUrl(String fromUrl) {
		this.fromUrl = fromUrl;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	public String getImages() {
		return this.images;
	}

	public void setImages(String images) {
		this.images = images;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getVisitSum() {
		return this.visitSum;
	}

	public void setVisitSum(Integer visitSum) {
		this.visitSum = visitSum;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getAreaTags() {
		return this.areaTags;
	}

	public void setAreaTags(String areaTags) {
		this.areaTags = areaTags;
	}

	public String getWorkTags() {
		return this.workTags;
	}

	public void setWorkTags(String workTags) {
		this.workTags = workTags;
	}

	public Integer getRank() {
		return this.rank;
	}

	public void setRank(Integer rank) {
		this.rank = rank;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
