package com.jite.hibgen.model;
// Generated 2018-3-26 10:06:46 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * TRedPkgPwd generated by hbm2java
 */
public class TRedPkgPwd implements java.io.Serializable {

	private Long id;
	private Integer type;
	private Integer unitm;
	private String cardNum;
	private String cardPwd;
	private Integer status;
	private String sentTo;
	private Date createDate;
	private Date updateDate;

	public TRedPkgPwd() {
	}

	public TRedPkgPwd(Integer type, Integer unitm, String cardNum, String cardPwd, Integer status, String sentTo,
			Date createDate, Date updateDate) {
		this.type = type;
		this.unitm = unitm;
		this.cardNum = cardNum;
		this.cardPwd = cardPwd;
		this.status = status;
		this.sentTo = sentTo;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public Integer getUnitm() {
		return this.unitm;
	}

	public void setUnitm(Integer unitm) {
		this.unitm = unitm;
	}

	public String getCardNum() {
		return this.cardNum;
	}

	public void setCardNum(String cardNum) {
		this.cardNum = cardNum;
	}

	public String getCardPwd() {
		return this.cardPwd;
	}

	public void setCardPwd(String cardPwd) {
		this.cardPwd = cardPwd;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getSentTo() {
		return this.sentTo;
	}

	public void setSentTo(String sentTo) {
		this.sentTo = sentTo;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
