package com.jite.hibgen.model;
// Generated 2018-3-26 10:06:46 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * TShowAppbanner generated by hbm2java
 */
public class TShowAppbanner implements java.io.Serializable {

	private Long id;
	private String imgUrl;
	private String linkUrl;
	private Integer rank;
	private Integer status;
	private Integer type;
	private Date createDate;
	private Date updateDate;

	public TShowAppbanner() {
	}

	public TShowAppbanner(String imgUrl, String linkUrl, Integer rank, Integer status, Integer type, Date createDate,
			Date updateDate) {
		this.imgUrl = imgUrl;
		this.linkUrl = linkUrl;
		this.rank = rank;
		this.status = status;
		this.type = type;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getImgUrl() {
		return this.imgUrl;
	}

	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl;
	}

	public String getLinkUrl() {
		return this.linkUrl;
	}

	public void setLinkUrl(String linkUrl) {
		this.linkUrl = linkUrl;
	}

	public Integer getRank() {
		return this.rank;
	}

	public void setRank(Integer rank) {
		this.rank = rank;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
