package com.jite.hibgen.model;
// Generated 2018-3-26 10:06:46 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * TShowCompanyStart generated by hbm2java
 */
public class TShowCompanyStart implements java.io.Serializable {

	private Long id;
	private Long companyId;
	private Integer rank;
	private Date createDate;
	private Date updateDate;

	public TShowCompanyStart() {
	}

	public TShowCompanyStart(Long companyId, Integer rank, Date createDate, Date updateDate) {
		this.companyId = companyId;
		this.rank = rank;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Long companyId) {
		this.companyId = companyId;
	}

	public Integer getRank() {
		return this.rank;
	}

	public void setRank(Integer rank) {
		this.rank = rank;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
