package com.jite.hibgen.model;
// Generated 2018-3-26 10:06:46 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * TShowCooperativeUnit generated by hbm2java
 */
public class TShowCooperativeUnit implements java.io.Serializable {

	private Long id;
	private String name;
	private String imgUrl;
	private String linkUrl;
	private Integer rank;
	private Integer status;
	private Date createDate;
	private Date updateDate;

	public TShowCooperativeUnit() {
	}

	public TShowCooperativeUnit(String name, String imgUrl, String linkUrl, Integer rank, Integer status,
			Date createDate, Date updateDate) {
		this.name = name;
		this.imgUrl = imgUrl;
		this.linkUrl = linkUrl;
		this.rank = rank;
		this.status = status;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getImgUrl() {
		return this.imgUrl;
	}

	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl;
	}

	public String getLinkUrl() {
		return this.linkUrl;
	}

	public void setLinkUrl(String linkUrl) {
		this.linkUrl = linkUrl;
	}

	public Integer getRank() {
		return this.rank;
	}

	public void setRank(Integer rank) {
		this.rank = rank;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
