package com.jite.hibgen.model;
// Generated 2018-3-26 10:06:46 by Hibernate Tools 4.3.1.Final

/**
 * TSystemEmployeeDepartment generated by hbm2java
 */
public class TSystemEmployeeDepartment implements java.io.Serializable {

	private Long empDeptId;
	private Long employeeId;
	private Long deptId;

	public TSystemEmployeeDepartment() {
	}

	public TSystemEmployeeDepartment(Long employeeId, Long deptId) {
		this.employeeId = employeeId;
		this.deptId = deptId;
	}

	public Long getEmpDeptId() {
		return this.empDeptId;
	}

	public void setEmpDeptId(Long empDeptId) {
		this.empDeptId = empDeptId;
	}

	public Long getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(Long employeeId) {
		this.employeeId = employeeId;
	}

	public Long getDeptId() {
		return this.deptId;
	}

	public void setDeptId(Long deptId) {
		this.deptId = deptId;
	}

}
