package com.jite.hibgen.model;
// Generated 2018-3-26 10:06:46 by Hibernate Tools 4.3.1.Final

/**
 * TSystemDepartment generated by hbm2java
 */
public class TSystemDepartment implements java.io.Serializable {

	private Long departmentId;
	private String departmentName;
	private String fullName;
	private String departmentCode;
	private Long parentDepartmentId;
	private String creator;
	private Long creatorId;
	private Long createDeptId;
	private String createDeptName;
	private String createDeptCode;
	private String memo;
	private Integer departmentType;
	private Long companyId;

	public TSystemDepartment() {
	}

	public TSystemDepartment(String departmentName, String fullName, String departmentCode, Long parentDepartmentId,
			String creator, Long creatorId, Long createDeptId, String createDeptName, String createDeptCode,
			String memo, Integer departmentType, Long companyId) {
		this.departmentName = departmentName;
		this.fullName = fullName;
		this.departmentCode = departmentCode;
		this.parentDepartmentId = parentDepartmentId;
		this.creator = creator;
		this.creatorId = creatorId;
		this.createDeptId = createDeptId;
		this.createDeptName = createDeptName;
		this.createDeptCode = createDeptCode;
		this.memo = memo;
		this.departmentType = departmentType;
		this.companyId = companyId;
	}

	public Long getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(Long departmentId) {
		this.departmentId = departmentId;
	}

	public String getDepartmentName() {
		return this.departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public String getDepartmentCode() {
		return this.departmentCode;
	}

	public void setDepartmentCode(String departmentCode) {
		this.departmentCode = departmentCode;
	}

	public Long getParentDepartmentId() {
		return this.parentDepartmentId;
	}

	public void setParentDepartmentId(Long parentDepartmentId) {
		this.parentDepartmentId = parentDepartmentId;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public Long getCreatorId() {
		return this.creatorId;
	}

	public void setCreatorId(Long creatorId) {
		this.creatorId = creatorId;
	}

	public Long getCreateDeptId() {
		return this.createDeptId;
	}

	public void setCreateDeptId(Long createDeptId) {
		this.createDeptId = createDeptId;
	}

	public String getCreateDeptName() {
		return this.createDeptName;
	}

	public void setCreateDeptName(String createDeptName) {
		this.createDeptName = createDeptName;
	}

	public String getCreateDeptCode() {
		return this.createDeptCode;
	}

	public void setCreateDeptCode(String createDeptCode) {
		this.createDeptCode = createDeptCode;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public Integer getDepartmentType() {
		return this.departmentType;
	}

	public void setDepartmentType(Integer departmentType) {
		this.departmentType = departmentType;
	}

	public Long getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Long companyId) {
		this.companyId = companyId;
	}

}
