package com.jite.hibgen.model;
// Generated 2018-3-26 10:06:46 by Hibernate Tools 4.3.1.Final

/**
 * TSystemRole generated by hbm2java
 */
public class TSystemRole implements java.io.Serializable {

	private Long roleId;
	private String roleName;
	private String creator;
	private Long creatorDeptId;
	private String jbpmRole;
	private Long companyId;

	public TSystemRole() {
	}

	public TSystemRole(String roleName, String creator, Long creatorDeptId, String jbpmRole, Long companyId) {
		this.roleName = roleName;
		this.creator = creator;
		this.creatorDeptId = creatorDeptId;
		this.jbpmRole = jbpmRole;
		this.companyId = companyId;
	}

	public Long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public Long getCreatorDeptId() {
		return this.creatorDeptId;
	}

	public void setCreatorDeptId(Long creatorDeptId) {
		this.creatorDeptId = creatorDeptId;
	}

	public String getJbpmRole() {
		return this.jbpmRole;
	}

	public void setJbpmRole(String jbpmRole) {
		this.jbpmRole = jbpmRole;
	}

	public Long getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Long companyId) {
		this.companyId = companyId;
	}

}
