package com.jite.hibgen.model;
// Generated 2018-3-26 10:06:46 by Hibernate Tools 4.3.1.Final

/**
 * TTmpHr generated by hbm2java
 */
public class TTmpHr implements java.io.Serializable {

	private long id;

	public TTmpHr() {
	}

	public TTmpHr(long id) {
		this.id = id;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

}
