package com.jite.hibgen.model;
// Generated 2018-3-26 10:06:46 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * TUserProfileSkill generated by hbm2java
 */
public class TUserProfileSkill implements java.io.Serializable {

	private Long id;
	private Date updateDate;
	private Date createDate;
	private String proficiency;
	private String skillTime;
	private String skillName;
	private Long accountId;

	public TUserProfileSkill() {
	}

	public TUserProfileSkill(Date updateDate, Date createDate, String proficiency, String skillTime, String skillName,
			Long accountId) {
		this.updateDate = updateDate;
		this.createDate = createDate;
		this.proficiency = proficiency;
		this.skillTime = skillTime;
		this.skillName = skillName;
		this.accountId = accountId;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getProficiency() {
		return this.proficiency;
	}

	public void setProficiency(String proficiency) {
		this.proficiency = proficiency;
	}

	public String getSkillTime() {
		return this.skillTime;
	}

	public void setSkillTime(String skillTime) {
		this.skillTime = skillTime;
	}

	public String getSkillName() {
		return this.skillName;
	}

	public void setSkillName(String skillName) {
		this.skillName = skillName;
	}

	public Long getAccountId() {
		return this.accountId;
	}

	public void setAccountId(Long accountId) {
		this.accountId = accountId;
	}

}
