package com.jite.hibgen.model;
// Generated 2018-3-26 10:06:46 by Hibernate Tools 4.3.1.Final

/**
 * TUserMajor generated by hbm2java
 */
public class TUserMajor implements java.io.Serializable {

	private Long id;
	private String root;
	private String subname;
	private String thirdname;

	public TUserMajor() {
	}

	public TUserMajor(String root, String subname, String thirdname) {
		this.root = root;
		this.subname = subname;
		this.thirdname = thirdname;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getRoot() {
		return this.root;
	}

	public void setRoot(String root) {
		this.root = root;
	}

	public String getSubname() {
		return this.subname;
	}

	public void setSubname(String subname) {
		this.subname = subname;
	}

	public String getThirdname() {
		return this.thirdname;
	}

	public void setThirdname(String thirdname) {
		this.thirdname = thirdname;
	}

}
