package com.jite.hibgen.model;
// Generated 2018-3-26 10:06:46 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * TUserProfileLanguages generated by hbm2java
 */
public class TUserProfileLanguages implements java.io.Serializable {

	private Long id;
	private String LExplain;
	private String LScore;
	private String LType;
	private String LOracy;
	private Date createDate;
	private Date updateDate;
	private Long accountId;
	private String languageType;
	private String oracy;
	private Float score;

	public TUserProfileLanguages() {
	}

	public TUserProfileLanguages(String LExplain, String LScore, String LType, String LOracy, Date createDate,
			Date updateDate, Long accountId, String languageType, String oracy, Float score) {
		this.LExplain = LExplain;
		this.LScore = LScore;
		this.LType = LType;
		this.LOracy = LOracy;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.accountId = accountId;
		this.languageType = languageType;
		this.oracy = oracy;
		this.score = score;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getLExplain() {
		return this.LExplain;
	}

	public void setLExplain(String LExplain) {
		this.LExplain = LExplain;
	}

	public String getLScore() {
		return this.LScore;
	}

	public void setLScore(String LScore) {
		this.LScore = LScore;
	}

	public String getLType() {
		return this.LType;
	}

	public void setLType(String LType) {
		this.LType = LType;
	}

	public String getLOracy() {
		return this.LOracy;
	}

	public void setLOracy(String LOracy) {
		this.LOracy = LOracy;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Long getAccountId() {
		return this.accountId;
	}

	public void setAccountId(Long accountId) {
		this.accountId = accountId;
	}

	public String getLanguageType() {
		return this.languageType;
	}

	public void setLanguageType(String languageType) {
		this.languageType = languageType;
	}

	public String getOracy() {
		return this.oracy;
	}

	public void setOracy(String oracy) {
		this.oracy = oracy;
	}

	public Float getScore() {
		return this.score;
	}

	public void setScore(Float score) {
		this.score = score;
	}

}
