package com.jite.hibgen.model;
// Generated 2018-3-26 10:06:46 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * TUserSchoolBackup generated by hbm2java
 */
public class TUserSchoolBackup implements java.io.Serializable {

	private Long id;
	private String name;
	private String shortName;
	private String logo;
	private String chargedDepart;
	private String level;
	private String province;
	private String proCode;
	private String address;
	private String homepage;
	private String telephone;
	private String description;
	private String comments;
	private Date createDate;
	private Date updateDate;

	public TUserSchoolBackup() {
	}

	public TUserSchoolBackup(String name, String shortName, String logo, String chargedDepart, String level,
			String province, String proCode, String address, String homepage, String telephone, String description,
			String comments, Date createDate, Date updateDate) {
		this.name = name;
		this.shortName = shortName;
		this.logo = logo;
		this.chargedDepart = chargedDepart;
		this.level = level;
		this.province = province;
		this.proCode = proCode;
		this.address = address;
		this.homepage = homepage;
		this.telephone = telephone;
		this.description = description;
		this.comments = comments;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getShortName() {
		return this.shortName;
	}

	public void setShortName(String shortName) {
		this.shortName = shortName;
	}

	public String getLogo() {
		return this.logo;
	}

	public void setLogo(String logo) {
		this.logo = logo;
	}

	public String getChargedDepart() {
		return this.chargedDepart;
	}

	public void setChargedDepart(String chargedDepart) {
		this.chargedDepart = chargedDepart;
	}

	public String getLevel() {
		return this.level;
	}

	public void setLevel(String level) {
		this.level = level;
	}

	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getProCode() {
		return this.proCode;
	}

	public void setProCode(String proCode) {
		this.proCode = proCode;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getHomepage() {
		return this.homepage;
	}

	public void setHomepage(String homepage) {
		this.homepage = homepage;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
