package com.jite.hibgen.model;
// Generated 2018-3-26 10:06:46 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * TUserBizcard generated by hbm2java
 */
public class TUserBizcard implements java.io.Serializable {

	private Long id;
	private Long accountId;
	private String volunteerNumber;
	private String realName;
	private Date birthday;
	private Integer sex;
	private String schoolName;
	private String schoolNameRoot;
	private String degree;
	private String curcarrier;
	private String major;
	private String majorRoot;
	private String majorSub;
	private String phoneNumber;
	private String emailAddress;
	private String headImage;
	private Date createDate;
	private Date updateDate;
	private Integer tuaStatus;
	private Integer tuaEmailVerified;
	private Integer tuaPhoneVerified;
	private Date tuaLastlogin;
	private String tupbLocation;
	private String tupbDescription;
	private String tupiAllintends;
	private Integer taauSixty;

	public TUserBizcard() {
	}

	public TUserBizcard(Long accountId, String volunteerNumber, String realName, Date birthday, Integer sex,
			String schoolName, String schoolNameRoot, String degree, String curcarrier, String major, String majorRoot,
			String majorSub, String phoneNumber, String emailAddress, String headImage, Date createDate,
			Date updateDate, Integer tuaStatus, Integer tuaEmailVerified, Integer tuaPhoneVerified, Date tuaLastlogin,
			String tupbLocation, String tupbDescription, String tupiAllintends, Integer taauSixty) {
		this.accountId = accountId;
		this.volunteerNumber = volunteerNumber;
		this.realName = realName;
		this.birthday = birthday;
		this.sex = sex;
		this.schoolName = schoolName;
		this.schoolNameRoot = schoolNameRoot;
		this.degree = degree;
		this.curcarrier = curcarrier;
		this.major = major;
		this.majorRoot = majorRoot;
		this.majorSub = majorSub;
		this.phoneNumber = phoneNumber;
		this.emailAddress = emailAddress;
		this.headImage = headImage;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.tuaStatus = tuaStatus;
		this.tuaEmailVerified = tuaEmailVerified;
		this.tuaPhoneVerified = tuaPhoneVerified;
		this.tuaLastlogin = tuaLastlogin;
		this.tupbLocation = tupbLocation;
		this.tupbDescription = tupbDescription;
		this.tupiAllintends = tupiAllintends;
		this.taauSixty = taauSixty;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getAccountId() {
		return this.accountId;
	}

	public void setAccountId(Long accountId) {
		this.accountId = accountId;
	}

	public String getVolunteerNumber() {
		return this.volunteerNumber;
	}

	public void setVolunteerNumber(String volunteerNumber) {
		this.volunteerNumber = volunteerNumber;
	}

	public String getRealName() {
		return this.realName;
	}

	public void setRealName(String realName) {
		this.realName = realName;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public Integer getSex() {
		return this.sex;
	}

	public void setSex(Integer sex) {
		this.sex = sex;
	}

	public String getSchoolName() {
		return this.schoolName;
	}

	public void setSchoolName(String schoolName) {
		this.schoolName = schoolName;
	}

	public String getSchoolNameRoot() {
		return this.schoolNameRoot;
	}

	public void setSchoolNameRoot(String schoolNameRoot) {
		this.schoolNameRoot = schoolNameRoot;
	}

	public String getDegree() {
		return this.degree;
	}

	public void setDegree(String degree) {
		this.degree = degree;
	}

	public String getCurcarrier() {
		return this.curcarrier;
	}

	public void setCurcarrier(String curcarrier) {
		this.curcarrier = curcarrier;
	}

	public String getMajor() {
		return this.major;
	}

	public void setMajor(String major) {
		this.major = major;
	}

	public String getMajorRoot() {
		return this.majorRoot;
	}

	public void setMajorRoot(String majorRoot) {
		this.majorRoot = majorRoot;
	}

	public String getMajorSub() {
		return this.majorSub;
	}

	public void setMajorSub(String majorSub) {
		this.majorSub = majorSub;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	public String getHeadImage() {
		return this.headImage;
	}

	public void setHeadImage(String headImage) {
		this.headImage = headImage;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Integer getTuaStatus() {
		return this.tuaStatus;
	}

	public void setTuaStatus(Integer tuaStatus) {
		this.tuaStatus = tuaStatus;
	}

	public Integer getTuaEmailVerified() {
		return this.tuaEmailVerified;
	}

	public void setTuaEmailVerified(Integer tuaEmailVerified) {
		this.tuaEmailVerified = tuaEmailVerified;
	}

	public Integer getTuaPhoneVerified() {
		return this.tuaPhoneVerified;
	}

	public void setTuaPhoneVerified(Integer tuaPhoneVerified) {
		this.tuaPhoneVerified = tuaPhoneVerified;
	}

	public Date getTuaLastlogin() {
		return this.tuaLastlogin;
	}

	public void setTuaLastlogin(Date tuaLastlogin) {
		this.tuaLastlogin = tuaLastlogin;
	}

	public String getTupbLocation() {
		return this.tupbLocation;
	}

	public void setTupbLocation(String tupbLocation) {
		this.tupbLocation = tupbLocation;
	}

	public String getTupbDescription() {
		return this.tupbDescription;
	}

	public void setTupbDescription(String tupbDescription) {
		this.tupbDescription = tupbDescription;
	}

	public String getTupiAllintends() {
		return this.tupiAllintends;
	}

	public void setTupiAllintends(String tupiAllintends) {
		this.tupiAllintends = tupiAllintends;
	}

	public Integer getTaauSixty() {
		return this.taauSixty;
	}

	public void setTaauSixty(Integer taauSixty) {
		this.taauSixty = taauSixty;
	}

}
