package com.jite.hibgen.model;
// Generated 2018-3-26 10:06:46 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * TUserProfileBasic generated by hbm2java
 */
public class TUserProfileBasic implements java.io.Serializable {

	private Long id;
	private Long accountId;
	private String personalHomepage;
	private String nationalOutlook;
	private String idCard;
	private String huKou;
	private String nation;
	private String curLocation;
	private Float weight;
	private Float height;
	private String zipCode;
	private String zipAddress;
	private String description;
	private Date createDate;
	private Date updateDate;

	public TUserProfileBasic() {
	}

	public TUserProfileBasic(Long accountId, String personalHomepage, String nationalOutlook, String idCard,
			String huKou, String nation, String curLocation, Float weight, Float height, String zipCode,
			String zipAddress, String description, Date createDate, Date updateDate) {
		this.accountId = accountId;
		this.personalHomepage = personalHomepage;
		this.nationalOutlook = nationalOutlook;
		this.idCard = idCard;
		this.huKou = huKou;
		this.nation = nation;
		this.curLocation = curLocation;
		this.weight = weight;
		this.height = height;
		this.zipCode = zipCode;
		this.zipAddress = zipAddress;
		this.description = description;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getAccountId() {
		return this.accountId;
	}

	public void setAccountId(Long accountId) {
		this.accountId = accountId;
	}

	public String getPersonalHomepage() {
		return this.personalHomepage;
	}

	public void setPersonalHomepage(String personalHomepage) {
		this.personalHomepage = personalHomepage;
	}

	public String getNationalOutlook() {
		return this.nationalOutlook;
	}

	public void setNationalOutlook(String nationalOutlook) {
		this.nationalOutlook = nationalOutlook;
	}

	public String getIdCard() {
		return this.idCard;
	}

	public void setIdCard(String idCard) {
		this.idCard = idCard;
	}

	public String getHuKou() {
		return this.huKou;
	}

	public void setHuKou(String huKou) {
		this.huKou = huKou;
	}

	public String getNation() {
		return this.nation;
	}

	public void setNation(String nation) {
		this.nation = nation;
	}

	public String getCurLocation() {
		return this.curLocation;
	}

	public void setCurLocation(String curLocation) {
		this.curLocation = curLocation;
	}

	public Float getWeight() {
		return this.weight;
	}

	public void setWeight(Float weight) {
		this.weight = weight;
	}

	public Float getHeight() {
		return this.height;
	}

	public void setHeight(Float height) {
		this.height = height;
	}

	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	public String getZipAddress() {
		return this.zipAddress;
	}

	public void setZipAddress(String zipAddress) {
		this.zipAddress = zipAddress;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
