package com.jite.hibgen.model;
// Generated 2018-3-26 10:06:46 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * TVersion generated by hbm2java
 */
public class TVersion implements java.io.Serializable {

	private Long versionId;
	private String versionName;
	private String versionCode;
	private Date createDate;
	private String appUrl;
	private String versionRemark;
	private Integer type;

	public TVersion() {
	}

	public TVersion(String versionName, String versionCode, Date createDate, String appUrl, String versionRemark,
			Integer type) {
		this.versionName = versionName;
		this.versionCode = versionCode;
		this.createDate = createDate;
		this.appUrl = appUrl;
		this.versionRemark = versionRemark;
		this.type = type;
	}

	public Long getVersionId() {
		return this.versionId;
	}

	public void setVersionId(Long versionId) {
		this.versionId = versionId;
	}

	public String getVersionName() {
		return this.versionName;
	}

	public void setVersionName(String versionName) {
		this.versionName = versionName;
	}

	public String getVersionCode() {
		return this.versionCode;
	}

	public void setVersionCode(String versionCode) {
		this.versionCode = versionCode;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getAppUrl() {
		return this.appUrl;
	}

	public void setAppUrl(String appUrl) {
		this.appUrl = appUrl;
	}

	public String getVersionRemark() {
		return this.versionRemark;
	}

	public void setVersionRemark(String versionRemark) {
		this.versionRemark = versionRemark;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

}
