package com.jite.hibgen.model.moveout;

// Generated 2015-6-9 23:02:56 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * THrCompanyStart generated by hbm2java
 */
public class THrCompanyStart implements java.io.Serializable {

	private Long id;
	private Long companyId;
	private String leader;
	private String leaderPic;
	private String leaderPosition;
	private String leaderDesc;
	private String scope;
	private String moneyFrom;
	private String moneyFromDesc;
	private Date createDate;
	private Date updateDate;

	public THrCompanyStart() {
	}

	public THrCompanyStart(Long companyId, String leader, String leaderPic,
			String leaderPosition, String leaderDesc, String scope,
			String moneyFrom, String moneyFromDesc, Date createDate,
			Date updateDate) {
		this.companyId = companyId;
		this.leader = leader;
		this.leaderPic = leaderPic;
		this.leaderPosition = leaderPosition;
		this.leaderDesc = leaderDesc;
		this.scope = scope;
		this.moneyFrom = moneyFrom;
		this.moneyFromDesc = moneyFromDesc;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Long companyId) {
		this.companyId = companyId;
	}

	public String getLeader() {
		return this.leader;
	}

	public void setLeader(String leader) {
		this.leader = leader;
	}

	public String getLeaderPic() {
		return this.leaderPic;
	}

	public void setLeaderPic(String leaderPic) {
		this.leaderPic = leaderPic;
	}

	public String getLeaderPosition() {
		return this.leaderPosition;
	}

	public void setLeaderPosition(String leaderPosition) {
		this.leaderPosition = leaderPosition;
	}

	public String getLeaderDesc() {
		return this.leaderDesc;
	}

	public void setLeaderDesc(String leaderDesc) {
		this.leaderDesc = leaderDesc;
	}

	public String getScope() {
		return this.scope;
	}

	public void setScope(String scope) {
		this.scope = scope;
	}

	public String getMoneyFrom() {
		return this.moneyFrom;
	}

	public void setMoneyFrom(String moneyFrom) {
		this.moneyFrom = moneyFrom;
	}

	public String getMoneyFromDesc() {
		return this.moneyFromDesc;
	}

	public void setMoneyFromDesc(String moneyFromDesc) {
		this.moneyFromDesc = moneyFromDesc;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
