package com.luo.hibgen.model;
// Generated 2017-4-4 23:45:13 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * THrJobBase generated by hbm2java
 */
public class THrJobBase implements java.io.Serializable {

	private Long id;
	private Long companyId;
	private String charType;
	private String name;
	private String seqNum;
	private String workType;
	private String workTypeRoot;
	private String workTypeSub;
	private String humanNumber;
	private String degree;
	private String workYears;
	private Integer westplanFlag;
	private String tags;
	private String location;
	private String department;
	private String departReportTo;
	private Integer departUnderCount;
	private String description;
	private Integer type;
	private Double salary;
	private Double salaryAbove;
	private Integer notShowSalary;
	private String status;
	private String mailtoFlag;
	private String mailtoAddress;
	private Date fromDate;
	private Date endDate;
	private Integer isHot;
	private Long creater;
	private Date createDate;
	private Long updater;
	private Date updateDate;

	public THrJobBase() {
	}

	public THrJobBase(Long companyId, String charType, String name, String seqNum, String workType, String workTypeRoot,
			String workTypeSub, String humanNumber, String degree, String workYears, Integer westplanFlag, String tags,
			String location, String department, String departReportTo, Integer departUnderCount, String description,
			Integer type, Double salary, Double salaryAbove, Integer notShowSalary, String status, String mailtoFlag,
			String mailtoAddress, Date fromDate, Date endDate, Integer isHot, Long creater, Date createDate,
			Long updater, Date updateDate) {
		this.companyId = companyId;
		this.charType = charType;
		this.name = name;
		this.seqNum = seqNum;
		this.workType = workType;
		this.workTypeRoot = workTypeRoot;
		this.workTypeSub = workTypeSub;
		this.humanNumber = humanNumber;
		this.degree = degree;
		this.workYears = workYears;
		this.westplanFlag = westplanFlag;
		this.tags = tags;
		this.location = location;
		this.department = department;
		this.departReportTo = departReportTo;
		this.departUnderCount = departUnderCount;
		this.description = description;
		this.type = type;
		this.salary = salary;
		this.salaryAbove = salaryAbove;
		this.notShowSalary = notShowSalary;
		this.status = status;
		this.mailtoFlag = mailtoFlag;
		this.mailtoAddress = mailtoAddress;
		this.fromDate = fromDate;
		this.endDate = endDate;
		this.isHot = isHot;
		this.creater = creater;
		this.createDate = createDate;
		this.updater = updater;
		this.updateDate = updateDate;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Long companyId) {
		this.companyId = companyId;
	}

	public String getCharType() {
		return this.charType;
	}

	public void setCharType(String charType) {
		this.charType = charType;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSeqNum() {
		return this.seqNum;
	}

	public void setSeqNum(String seqNum) {
		this.seqNum = seqNum;
	}

	public String getWorkType() {
		return this.workType;
	}

	public void setWorkType(String workType) {
		this.workType = workType;
	}

	public String getWorkTypeRoot() {
		return this.workTypeRoot;
	}

	public void setWorkTypeRoot(String workTypeRoot) {
		this.workTypeRoot = workTypeRoot;
	}

	public String getWorkTypeSub() {
		return this.workTypeSub;
	}

	public void setWorkTypeSub(String workTypeSub) {
		this.workTypeSub = workTypeSub;
	}

	public String getHumanNumber() {
		return this.humanNumber;
	}

	public void setHumanNumber(String humanNumber) {
		this.humanNumber = humanNumber;
	}

	public String getDegree() {
		return this.degree;
	}

	public void setDegree(String degree) {
		this.degree = degree;
	}

	public String getWorkYears() {
		return this.workYears;
	}

	public void setWorkYears(String workYears) {
		this.workYears = workYears;
	}

	public Integer getWestplanFlag() {
		return this.westplanFlag;
	}

	public void setWestplanFlag(Integer westplanFlag) {
		this.westplanFlag = westplanFlag;
	}

	public String getTags() {
		return this.tags;
	}

	public void setTags(String tags) {
		this.tags = tags;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	public String getDepartReportTo() {
		return this.departReportTo;
	}

	public void setDepartReportTo(String departReportTo) {
		this.departReportTo = departReportTo;
	}

	public Integer getDepartUnderCount() {
		return this.departUnderCount;
	}

	public void setDepartUnderCount(Integer departUnderCount) {
		this.departUnderCount = departUnderCount;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public Double getSalary() {
		return this.salary;
	}

	public void setSalary(Double salary) {
		this.salary = salary;
	}

	public Double getSalaryAbove() {
		return this.salaryAbove;
	}

	public void setSalaryAbove(Double salaryAbove) {
		this.salaryAbove = salaryAbove;
	}

	public Integer getNotShowSalary() {
		return this.notShowSalary;
	}

	public void setNotShowSalary(Integer notShowSalary) {
		this.notShowSalary = notShowSalary;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getMailtoFlag() {
		return this.mailtoFlag;
	}

	public void setMailtoFlag(String mailtoFlag) {
		this.mailtoFlag = mailtoFlag;
	}

	public String getMailtoAddress() {
		return this.mailtoAddress;
	}

	public void setMailtoAddress(String mailtoAddress) {
		this.mailtoAddress = mailtoAddress;
	}

	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Integer getIsHot() {
		return this.isHot;
	}

	public void setIsHot(Integer isHot) {
		this.isHot = isHot;
	}

	public Long getCreater() {
		return this.creater;
	}

	public void setCreater(Long creater) {
		this.creater = creater;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Long getUpdater() {
		return this.updater;
	}

	public void setUpdater(Long updater) {
		this.updater = updater;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
